---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/consul-replicate --version
    register: consul_replicate_test_output
  - name: consul-replicate --version
    debug:
      msg: '{{ consul_replicate_test_output.stderr }}'
